CREATE DATABASE MOVIE_MANGMENT; 
USE MOVIE_MANGMENT;
CREATE TABLE MOVIE (
MOVIE_ID INT PRIMARY KEY NOT NULL,
MOVIE_NAME VARCHAR(25) NOT NULL,
YEAR_D INT,
DEURATION DECIMAL(2,2),
GENERS VARCHAR(25)
);

CREATE TABLE PRODUCTION (
PRODUCTION_ID INT PRIMARY KEY NOT NULL,
PRODUCTION_NAME VARCHAR(25),
ADDRESS VARCHAR(25)
);
ALTER TABLE MOVIE ADD COLUMN PRODUCTION_ID INT;

ALTER TABLE MOVIE 
ADD CONSTRAINT FK_PRODUCTION_ID
FOREIGN KEY (PRODUCTION_ID) 
REFERENCES PRODUCTION (PRODUCTION_ID);

CREATE TABLE Person (
    PersonID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    DateOfBirth DATE
);

CREATE TABLE ACTORS (
    ACTORS_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    DateOfBirth DATE,
    APPEAR VARCHAR(10) 
);


